### PR TITLE
Add local_inner_macros to all macro_exports

### PR DESCRIPTION
**Pull request by cramertj**
This makes the bitfield macros usable from the 2018
edition without needing to import the helper macros
they call.

See https://github.com/bitflags/bitflags/pull/165 for similar PR against bitflags.

### CODE REVIEW

**Comment by dzamlo** [comment]
Thanks!

**Comment by dzamlo** [comment]
Your improvement is available in version 0.13.1

**Comment by cramertj** [comment]
Great, thanks so much for the quick release!

**Pull request merged**
