### PR TITLE
Easily Derive Bitwise Operations

### PR DESCRIPTION
**Pull request by PokeJofeJr4th**
This pull request will extend the macro syntax with optional lines of the form `impl BitOr;` to generate basic implementations for the common bitwise operators.

### CODE REVIEW

**Comment by dzamlo** [comment]
Very nice piece of code!

The only thing missing is some mention in the documentation.

**Comment by PokeJofeJr4th** [comment]
I'm not sure if I made the right call merging the assignment versions of the operators. Should we plan for a case where someone would want to derive `BitAnd` but not `BitAndAssign`?

**Comment by PokeJofeJr4th** [comment]
FYI other than that, and a version increment, I believe this is ready to merge

**Comment by dzamlo** [comment]
I think you made the right call.  I will release a new version with your changes ASAP.

**Comment by dzamlo** [comment]
Released as v0.16.0

**Pull request merged**
